line-length = 160
indent-width = 2
target-version = "py311"
extend-include = ["*.ipynb"]

[lint]
select = ["E", "F", "W", "PIE", "C4", "ISC", "RUF008", "RUF100", "A", "B", "TID251", "I001", "I002"]
ignore = ["E741", "E402", "C408", "ISC003", "B027", "B024"]

[lint.isort]
known-first-party = ["cereal", "panda", "opendbc"]
known-local-folder = ["openpilot", "notebooks"]
no-lines-before = ["local-folder"]

[format]
quote-style = "single"
line-ending = "lf"
